In [1]:
import numpy as np
from numpy import linalg

# Задание 1
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [2]:
N = 10
np_n = np.arange(N-1, -1, -1)
print(np_n)
print(type(np_n))

[9 8 7 6 5 4 3 2 1 0]
<class 'numpy.ndarray'>


# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [3]:
diagonal = np.diag(np_n)
sum_diag = np.sum(np.diag(diagonal))
print(f'диагональная матрица:\n{diagonal}')
print(f'сумма значений диагональной матрицы: {sum_diag}')

диагональная матрица:
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
сумма значений диагональной матрицы: 45


In [4]:
np.sum(np.diag(diagonal))

45

# Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [6]:
i = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
j = np.array([4, 12, -3])
k = linalg.solve(i, j)
x = k[0]
y = k[1]
z = k[2]
print(f'значения переменных:\nx = {x}\ny = {y}\nz = {z}')

значения переменных:
x = 0.4666666666666668
y = 3.844444444444444
z = -5.555555555555555
